// System chart of accounts (mirrors the reference seed of 58 accounts)
export interface SeedAccount {
  key: string;
  name: string;
  type: 'asset' | 'liability' | 'equity' | 'income' | 'expense';
  subType: string;
  isGroup?: boolean;
  isSystem?: boolean;
  parentKey?: string;
}

export const SYSTEM_ACCOUNTS: SeedAccount[] = [
  { key: 'accounts_payable', name: 'Accounts Payable', type: 'liability', subType: 'accounts_payable', isSystem: true },
  { key: 'accounts_receivable', name: 'Accounts Receivable', type: 'asset', subType: 'accounts_receivable', isSystem: true },
  { key: 'adjustment', name: 'Adjustment', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'advance_tax', name: 'Advance Tax', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'bad_debts', name: 'Bad Debts', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'bank_fees', name: 'Bank Fees and Charges', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'brokerage_advance', name: 'Brokerage Advance', type: 'asset', subType: 'other_current_asset' },
  { key: 'brokerage_expense', name: 'Brokerage Expense', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'brokerage_payable', name: 'Brokerage Payable', type: 'liability', subType: 'other_current_liability' },
  { key: 'cogs', name: 'Cost of Goods Sold', type: 'expense', subType: 'cost_of_goods_sold', isSystem: true },
  { key: 'depreciation', name: 'Depreciation Expense', type: 'expense', subType: 'expense' },
  { key: 'dimension_adjustments', name: 'Dimension Adjustments', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'discount_allowed', name: 'Discount Allowed', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'discount_received', name: 'Discount Received', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'drawings', name: 'Drawings', type: 'equity', subType: 'equity', isSystem: true },
  { key: 'employee_advance', name: 'Employee Advance', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'employee_reimbursements', name: 'Employee Reimbursements', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'exchange_gain_loss', name: 'Exchange Gain or Loss', type: 'expense', subType: 'other_expense', isSystem: true },
  { key: 'general_income', name: 'General Income', type: 'income', subType: 'income', isSystem: true },
  { key: 'gst_payable', name: 'GST Payable', type: 'liability', subType: 'other_current_liability', isGroup: true, isSystem: true },
  { key: 'output_cess', name: 'Output CESS', type: 'liability', subType: 'other_current_liability', isSystem: true, parentKey: 'gst_payable' },
  { key: 'output_cgst', name: 'Output CGST', type: 'liability', subType: 'other_current_liability', isSystem: true, parentKey: 'gst_payable' },
  { key: 'output_igst', name: 'Output IGST', type: 'liability', subType: 'other_current_liability', isSystem: true, parentKey: 'gst_payable' },
  { key: 'output_sgst', name: 'Output SGST', type: 'liability', subType: 'other_current_liability', isSystem: true, parentKey: 'gst_payable' },
  { key: 'input_tax_credits', name: 'Input Tax Credits', type: 'asset', subType: 'other_current_asset', isGroup: true, isSystem: true },
  { key: 'input_cess', name: 'Input CESS', type: 'asset', subType: 'other_current_asset', isSystem: true, parentKey: 'input_tax_credits' },
  { key: 'input_cgst', name: 'Input CGST', type: 'asset', subType: 'other_current_asset', isSystem: true, parentKey: 'input_tax_credits' },
  { key: 'input_igst', name: 'Input IGST', type: 'asset', subType: 'other_current_asset', isSystem: true, parentKey: 'input_tax_credits' },
  { key: 'input_sgst', name: 'Input SGST', type: 'asset', subType: 'other_current_asset', isSystem: true, parentKey: 'input_tax_credits' },
  { key: 'interest_income', name: 'Interest Income', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'inventory_asset', name: 'Inventory Asset', type: 'asset', subType: 'stock', isSystem: true },
  { key: 'late_fee_income', name: 'Late Fee Income', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'lodging', name: 'Lodging', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'opening_balance_adjustments', name: 'Opening Balance Adjustments', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'opening_balance_offset', name: 'Opening Balance Offset', type: 'equity', subType: 'equity', isSystem: true },
  { key: 'other_charges', name: 'Other Charges', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'other_expenses', name: 'Other Expenses', type: 'expense', subType: 'other_expense', isSystem: true },
  { key: 'owners_equity', name: "Owner's Equity", type: 'equity', subType: 'equity', isSystem: true },
  { key: 'payable_write_off', name: 'Payable Write Off', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'petty_cash', name: 'Petty Cash', type: 'asset', subType: 'cash', isSystem: true },
  { key: 'prepaid_expense', name: 'Prepaid Expense', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'rent_expense', name: 'Rent Expense', type: 'expense', subType: 'expense' },
  { key: 'retained_earnings', name: 'Retained Earnings', type: 'equity', subType: 'equity', isSystem: true },
  { key: 'reverse_charge_tax_input', name: 'Reverse Charge Tax Input but not due', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'salaries_wages', name: 'Salaries and Employee Wages', type: 'expense', subType: 'expense' },
  { key: 'salary_expense', name: 'Salary Expense', type: 'expense', subType: 'expense' },
  { key: 'sales', name: 'Sales', type: 'income', subType: 'income', isSystem: true },
  { key: 'sales_to_customers_cash', name: 'Sales to Customers (Cash)', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'shipping_charge', name: 'Shipping Charge', type: 'income', subType: 'other_income', isSystem: true },
  { key: 'tax_payable', name: 'Tax Payable', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'tcs_payable', name: 'TCS Payable', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'tcs_receivable', name: 'TCS Receivable', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'tds_payable', name: 'TDS Payable', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'tds_receivable', name: 'TDS Receivable', type: 'asset', subType: 'other_current_asset', isSystem: true },
  { key: 'uncategorized', name: 'Uncategorized', type: 'expense', subType: 'expense', isSystem: true },
  { key: 'undeposited_funds', name: 'Undeposited Funds', type: 'asset', subType: 'cash', isSystem: true },
  { key: 'unearned_revenue', name: 'Unearned Revenue', type: 'liability', subType: 'other_current_liability', isSystem: true },
  { key: 'write_off_expense', name: 'Write-off Expense', type: 'expense', subType: 'expense', isSystem: true },
];

export const DEFAULT_FIRM_SETTINGS = {
  hideBrokerFields: false,
  contactIsFirmwise: false,
  contactMobileCompulsory: true,
  allowRepeatedMobile: false,
  customerCreditLimit: false,
  contactDisplayFormat: '##Serial No##-##Company Name## (##Mobile No##)',
  itemQuantityDecimalRate: 2,
  stockValuationMethod: 'fifo',
  serializedInventoryTracking: false,
  batchLotTracking: false,
  stockTransferType: 'direct',
  stockTransferRate: 'manually',
  showSkuSeries: false,
  showMrp: false,
  displayImage: false,
  paymentTransactionType: 'bill_to_bill',
  reportingMethod: 'accrual',
  discountMode: 'none',
  discountMinusSign: false,
  enableAdjustments: true,
  enableShippingCharges: false,
  enableSalesperson: false,
  roundingMode: 'none',
  autoRoundTdsTcs: false,
  trackInventoryForPo: false,
  allowedNegativeStockSo: false,
  allowedNegativeStockInvoice: false,
  allowedNegativeStockDebitNote: false,
  allowedNegativeStockTransfer: false,
  showNegativeStockAlert: false,
  taxInclusivity: 'both',
  termsBillwise: { invoice: false, estimate: false, proforma: false, purchase_order: false },
  requireCustomer: true,
  showSaveAsDraftButton: true,
  showProductPastData: false,
  autoFillRateFromPastData: false,
  displayPcsColumn: false,
  purchaseMemoBillNoMandatory: false,
  allowCustomerWiseProductRate: false,
  useDateWisePrice: false,
  printCopies: 1,
  selectTemplateWhileSharing: false,
  labProcessRequireApproval: false,
  defaultTaxGroupId: null,
  lowStockReminder: false,
};
